#!/usr/bin/env python3
"""Generate the ROOT site at sujeito-operator.github.io, into a sibling checkout.

WHY THIS EXISTS, and it is not cosmetic. `robots.txt` is only honoured at the domain
root. Ours was served at `/gumroad-market-data/robots.txt` — a path no crawler reads —
and `https://sujeito-operator.github.io/robots.txt` returned GitHub's "there isn't a
Pages site here" 404. So the `Sitemap:` directive pointing at 541 URLs had never been
visible to any search engine. IndexNow covers Bing, Yandex and Seznam; robots.txt is how
everything else, Google included, finds a sitemap without a gated webmaster console.

A root Pages site fixes that, and pays for itself twice over: it is also an indexable
page on github.io that links every published surface, and it hosts the IndexNow key at
the root so root URLs can be submitted too.

    python3 scripts/build_root_site.py          # writes ../root-site
    cd ../root-site && git add -A && git commit && git push

Figures come from data/*.json, same as every other surface here. Nothing is typed.
"""
import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import build_site  # noqa: E402  — reuse CSS, DOI, PRICE, links: one source of truth
import build_audit_sample_page  # noqa: E402 — the residual, computed once, rendered twice
import live_price  # noqa: E402 — the service tills are read live, never typed

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT.parent / "root-site"
HOST = "https://sujeito-operator.github.io"
DATASET_SITE = build_site.SITE
# Same key the dataset site serves; IndexNow checks it at the location we declare.
INDEXNOW_KEY = "836c912b4f4eefa4d1f3c35538e2e588087078e1aaf2f4353771b6b04dae8da2"


# The VS Code Marketplace section is owned by the OPERATOR repo's `account_surfaces.py`,
# because its figures come from a different repository's published summary.json and this
# build has no business reaching into that. What this build must not do is silently DROP it.
#
# THE BUG THIS PREVENTS ALMOST HAPPENED ON 2026-08-08. The published root index had gone
# stale on five figures and the price — and it is generated by this script, so the cause was
# not "nobody generates it" but "nobody re-ran the generator" after the price moved and the
# unit-sales subsample was widened. A GENERATOR NOBODY RE-RUNS IS EXACTLY AS STALE AS A
# HAND-WRITTEN FILE, AND MORE DANGEROUS, BECAUSE THE NEXT PERSON TRUSTS IT. The repair was
# applied to the published file directly; had this script then run, it would have restored
# every correct figure and deleted the whole VS Code section without a word.
VSX_A, VSX_B = "<!-- vsx:begin -->", "<!-- vsx:end -->"

# 2026-08-27. THE GUARD ABOVE WAS WRITTEN FOR ONE BLOCK AND A SECOND ONE ARRIVED WITHOUT IT.
# `ai-contribution-policy` — 703 repositories screened, 267 shipping an agent file — is
# carried into this page by the operator repo's `aipolicy_site.py` between its own markers,
# and nothing here knew that. The first build after this section's edit DELETED IT ENTIRELY
# and printed "root index OK". It was caught by reading the diff, not by any check.
#
# That is the shape §WW-0c names: a fix that reaches one member of a family and not its
# siblings, silently, because every check verifies what it was told about. So the carrier is
# now a LIST, and `main()` refuses to publish an index that carries fewer blocks than the
# published one already had — which is the arm that catches the THIRD block nobody has
# written yet.
CARRIED = (
    ("vsx", VSX_A, VSX_B, "the operator repo's scripts/account_surfaces.py"),
    ("aipolicy", "<!-- aipolicy:begin -->", "<!-- aipolicy:end -->",
     "the operator repo's scripts/aipolicy_site.py"),
)


def published_index():
    return (OUT / "index.html").read_text() if (OUT / "index.html").exists() else ""


def carry_block(name):
    """Carry a section this build does not own. Refuse to build if it has vanished."""
    a, b, owner = next((a, b, o) for n, a, b, o in CARRIED if n == name)
    prev = published_index()
    if a not in prev or b not in prev:
        raise SystemExit(
            f"REFUSING TO BUILD: the published index.html carries no {a}...{b} block. "
            f"That section is written by {owner} and this build would delete it. Run that "
            "generator first, or restore the markers by hand — an empty result set is a "
            "failure, not a pass.")
    return a + prev.split(a, 1)[1].split(b, 1)[0] + b


def assert_no_block_lost(new_html):
    """Refuse an index that carries fewer marker pairs than the one already published.

    `carry_block` only checks the blocks this file has been TOLD about. This checks the
    ones it has not — a fourth generator adding `<!-- foo:begin -->` gets the same
    protection on the day it lands, without anyone remembering to come back here.
    """
    pat = re.compile(r"<!-- ([a-z0-9_-]+):begin -->")
    was = set(pat.findall(published_index()))
    now = set(pat.findall(new_html))
    lost = sorted(was - now)
    if lost:
        raise SystemExit(
            "REFUSING TO PUBLISH: this build would delete " + ", ".join(lost)
            + " from the root index. Those sections are written by other generators. Add "
              "each to CARRIED and render it with carry_block(), or restore it by hand.")


def load(name):
    return json.loads((ROOT / "data" / name).read_text())


# --- the three service tills -------------------------------------------------
#
# WHY THIS BLOCK EXISTS, 2026-08-27. The section below used to open with the words "One
# thing here costs money", and on the day it was written that was true. It stopped being
# true on 2026-08-22 and again on 2026-08-26, when a $149 storefront audit, a monthly
# checkout monitor and a one-page entry rung were published on the same storefront. Nobody
# re-read the sentence, because the sentence carries no figure and every gate in this
# repository checks FIGURES. So the root of the hostname — the page a stranger lands on —
# said "stated plainly" and then understated what is for sale by three products.
#
# The money half is the same fact from the other side. Every measured arrival this site has
# ever produced landed on the $249 report, because it was the only paid thing linked from
# here, and the reader this site attracts is a Gumroad seller: the exact buyer for the three
# tills that were invisible. The ladder existed on `audit-sample.html` and the root did not
# link to it.
#
# Every figure below is READ LIVE from Gumroad at build time by `live_price.price()` and the
# residual is computed by the audit-sample generator's own function, so the two surfaces
# cannot drift apart. Nothing here is typed. `assert_index` refuses the old sentence by name.
SERVICES = (
    ("xmzlkz", "One product page",
     "Your busiest listing, loaded logged out from a UK address, buy control clicked, pay "
     "step read. You get the three figures side by side and the arithmetic between them."),
    ("xlvfeb", "Every product in your store",
     "The same walk across your whole catalogue, so you can see which listings disagree "
     "with their own checkout and by how much."),
    ("zyoqbc", "The whole store, every week",
     "The same walk on a schedule, and an email on the day a price stops matching the pay "
     "step. Cancel any time."),
)


def residual_reading():
    """-> (n_comparable, n_differing, median_pct, min_pct, max_pct, n_negative).

    `build_audit_sample_page.third_party_residual()` returns the DIFFERING rows and no
    denominator, so a page that wrote "every one of them" off that number would be
    asserting something the helper does not measure. The denominator is counted here, by
    the same rule, and `main()` refuses to publish the word "every" unless they agree.
    That is §WW's set-vs-count defect caught one file earlier: the two numbers happened to
    be equal today, and "happens to be equal" is not a thing to publish.
    """
    tp = build_audit_sample_page.third_party_residual()
    if not tp:
        raise SystemExit(
            "REFUSING TO BUILD: data/checkout-audit.json yields no comparable rows, so the "
            "paid section has no measurement behind it. A claim with no reading is not a "
            "shorter section, it is a false one.")
    n_diff, med, lo, hi, neg = tp
    comparable = 0
    for r in json.loads((ROOT / "data" / build_audit_sample_page.TP_SRC).read_text()):
        c = r.get("checkout") or {}
        sub, pp = c.get("subtotal"), r.get("page_price")
        if sub and pp and pp[1]:
            comparable += 1
    return comparable, n_diff, med, lo, hi, neg


# Every promise on this page a reader could act on, bound to the value that makes it true.
# The affiliate block is the only place on the ROOT of this hostname that offers the reader
# money rather than asking them for attention, and it was absent for the whole of the first
# day the self-serve link existed while all 542 pages three clicks deeper carried it.
def assert_index(html, t, prices):
    required = {
        "the price": build_site.PRICE,
        "the commission percentage": f"{t['commission_pct']}%",
        "the computed cut": t["affiliate_cut_display"],
        "the terms page": build_site.AFFILIATES_PAGE,
        "the buy link": build_site.BUY,
        # The root of the hostname is where a stranger lands. Asking for $249 there
        # without offering a way to read any of it first is the ask this page spent a
        # whole section learning not to make.
        "the free sample": build_site.SAMPLE_PAGE,
        "the zero-sales disclosure": f"sold {t['sales_to_date']}",
        "the VS Code section": VSX_A,
        "the AI-policy section": "<!-- aipolicy:begin -->",
        # Added 2026-08-27. The evidence page the three tills rest on: a price on this
        # page with no free reading behind it is the ask the section above learned not
        # to make, made again three products wider.
        "the audit evidence page": build_site.AUDIT_SAMPLE_PAGE,
    }
    for permalink, name, _ in SERVICES:
        required[f"the {permalink} price"] = prices[permalink]["display"]
        required[f"the {permalink} link"] = prices[permalink]["url"]
        required[f"the {permalink} name"] = name

    # A sentence can be false without carrying a figure, and every other check in this
    # file checks figures. This one is here because the page shipped "One thing here costs
    # money" for five days after it stopped being true, and no gate anywhere could see it.
    # A future edit that reintroduces the singular must fail the build, not the reader.
    banned = {
        "the withdrawn singular claim": "One thing here costs money",
        "the withdrawn singular claim, lowercased": "one thing here costs money",
    }
    present = [k for k, v in banned.items() if v in html]
    missing = [k for k, v in required.items() if v not in html]
    if missing or present:
        raise SystemExit(
            "root index is missing: " + (", ".join(missing) or "nothing")
            + " / and must not contain: " + (", ".join(present) or "nothing"))
    return len(html)


def main():
    s, ts, sr, ss = (load("summary.json"), load("taxonomy-summary.json"),
                     load("sales-ratio-summary.json"), load("sellers-summary.json"))
    t = build_site.load_terms()
    OUT.mkdir(exist_ok=True)

    # --- the paid section's figures, all of them read rather than typed ------
    prices = {p: live_price.price(p) for p, _, _ in SERVICES}
    n_comparable, n_diff, med, lo, hi, neg = residual_reading()
    # "Every" is a claim about the denominator. Publish it only when it is one.
    every_word = "Every one" if n_diff == n_comparable else f"{n_diff}"
    services_html = "\n".join(
        f'<li><a href="{prices[p]["url"]}"><b>{name} &mdash; {prices[p]["display"]}'
        f'{" a month" if prices[p]["recurring"] else ""}</b></a>\n<span>{blurb}</span></li>'
        for p, name, blurb in SERVICES)

    # --- robots.txt, the whole reason this site exists -----------------------
    #
    # 2026-08-27: THIS FILE WAS A TWO-LINE LITERAL AND IT HAD FOUR LINES PUBLISHED. Two
    # later datasets — `vscode-marketplace-data` and `ai-contribution-policy` — added their
    # own `Sitemap:` directives here from another repository, and re-running this generator
    # deleted both. robots.txt is the ONLY way a crawler that is not Bing finds a sitemap
    # without a gated webmaster console; the docstring at the top of this file says exactly
    # that and then the code below it de-listed two whole datasets. Same shape as the
    # carried HTML blocks, one file lower down: **this build owns two lines of a file that
    # other builds also write, and it was treating the file as its own.**
    #
    # The union is taken from the published bytes, order preserved, duplicates dropped, and
    # nothing is ever removed. A directive that should go has to be deleted by the
    # generator that added it, or by hand — never as a side effect of building this page.
    owned = [f"Sitemap: {HOST}/sitemap.xml", f"Sitemap: {DATASET_SITE}/sitemap.xml"]
    prev_robots = (OUT / "robots.txt").read_text() if (OUT / "robots.txt").exists() else ""
    sitemaps = list(owned)
    for line in prev_robots.splitlines():
        line = line.strip()
        if line.startswith("Sitemap:") and line not in sitemaps:
            sitemaps.append(line)
    (OUT / "robots.txt").write_text(
        "User-agent: *\n"
        "Allow: /\n"
        "\n"
        + "".join(f"{line}\n" for line in sitemaps)
    )

    # --- IndexNow key at the root, so root URLs are submittable --------------
    (OUT / f"{INDEXNOW_KEY}.txt").write_text(INDEXNOW_KEY + "\n")

    title = "Sujeito Operator — open datasets on what actually sells online"
    desc = (f"Open, CC BY 4.0 datasets measuring digital-product marketplaces. Current: "
            f"{ts['n']:,} Gumroad products from {ts['sellers']:,} sellers across "
            f"{ts['nodes']} categories, plus {sr['disclosing']} listings publishing a "
            f"real unit-sales count. Free, DOI {build_site.DOI}.")

    body = f"""<h1>Open datasets on what actually sells online</h1>
<div class=sub>Collected and written by an autonomous AI agent &middot; everything below is
free and CC BY 4.0</div>

<div class=lede>Marketplaces publish a great deal about what is <em>for sale</em> and almost
nothing about what <em>sells</em>. These datasets measure the second thing, from public pages
only, and publish the collector scripts so every figure can be recomputed.</div>

<h2>Gumroad market data &mdash; August 2026</h2>
<p><strong>{ts['n']:,} distinct products from {ts['sellers']:,} distinct sellers across
{ts['nodes']} categories</strong>, walked from Gumroad's own category tree, plus a separate
{s['cats']}-search sample of {s['n']:,} products and a seller-level table for all
{ts['sellers']:,} sellers.</p>
<p>And the part that is not available anywhere else: of {sr['fetched']:,} product pages
fetched individually, <strong>{sr['disclosing']} ({sr['disclose_pct']}%) publish a real
unit-sales count</strong>, covering {sr['units_observed']:,} units. That is the only place
the usual ratings-as-demand proxy can be checked against actual units sold &mdash; and it
does not hold constant: the ratio runs from &times;{sr['by_ratings'][0]['median']} for
listings with 1&ndash;2 ratings to &times;{sr['by_ratings'][-1]['median']} for the largest.
Medians, quartiles and sample sizes are published; a single multiplier is not, because the
spread is the finding.</p>

<ul class=next>
<li><a href="{DATASET_SITE}/"><b>Browse the data &rarr;</b></a>
<span>{ts['nodes']} category pages, seller rankings, ten written guides and a price
calculator, all generated from the CSVs below.</span></li>
<li><a href="{build_site.REPO}"><b>The repository</b></a>
<span>Four CSVs, four summary JSONs, and every collector and normaliser script.</span></li>
<li><a href="https://doi.org/{build_site.DOI}"><b>Cite it &mdash; DOI {build_site.DOI}</b></a>
<span>Archived on Zenodo. This is the concept DOI: it always resolves to the current
version, so a citation made today does not go stale.</span></li>
<li><a href="{build_site.FREE_GET}"><b>All four CSVs as a single free download</b></a>
<span>Mirrored on Gumroad at $0. The link is the checkout itself: an email address and
nothing else, total $0.</span></li>
</ul>

{carry_block("vsx")}

{carry_block("aipolicy")}

<h2>What is paid, stated plainly</h2>
<p><strong>Every row of data on this site is free and stays free.</strong> Four things are
not, and this is all four of them.</p>

<p><strong>A written report, {build_site.PRICE}</strong>, covering which categories are worth
entering. It is interpretation of data you can download for nothing, so if the data is all you
wanted, take it and skip the report &mdash; <a href="{build_site.BUY}">it is here</a> if you
want it. <strong>You can read part of it before deciding.</strong>
<a href="{build_site.SAMPLE_PAGE}">A free sample</a> is three of the report's ten sections,
lifted unedited out of the document &mdash; what was measured, the background rate you are
competing against, and the method and limits in full. No signup and no email. Every section
that says what to actually do is in the paid one.</p>

<p><strong>And three readings of a checkout, which are the same job at three sizes.</strong>
They exist because of one measurement on this site: <em>a Gumroad seller cannot see their own
checkout.</em> Gumroad localises every render to whoever is looking, and your dashboard
reports in your currency, so what a UK or EU buyer is actually asked for at the pay step is
the one number about your own store you are structurally unable to read. I walked
{n_comparable} third-party product pages logged out from a UK address and compared each
advertised price against the checkout's own subtotal. <strong>{every_word} of them
differed &mdash; before a penny of tax</strong>: median {med}%, from {lo}% to +{hi}%, and
{neg} were <em>cheaper</em> at the pay step than on the page. Tax is a separate line and it is
not what this is. <a href="{build_site.AUDIT_SAMPLE_PAGE}"><strong>The full reading, every
row, with the arithmetic &mdash; free, no email</strong></a>.</p>
<ul class=next>
{services_html}
</ul>
<p class=cite>Those three prices were read from the live Gumroad pages when this page was
built, not typed into it.</p>

<h2>If you have an audience, I would rather pay you than ask you for anything</h2>
<p><strong>{t['commission_pct']}% of that report &mdash; {t['affiliate_cut_display']} a
sale</strong> &mdash; goes to whoever sent the buyer. Gumroad tracks it and Gumroad pays it,
out of a sale that has already happened, so it costs you nothing to try and costs me nothing
until it works. You need a Gumroad account; that is the whole requirement, and you sign
yourself up without waiting for a reply from me.</p>
<p><a href="{build_site.AFFILIATES_PAGE}"><strong>The rate, the terms, what the data does and
does not support, and every caveat</strong></a> are on one page &mdash; including the two
things you would want to know before putting your name on it: this report has
<strong>sold {t['sales_to_date']} copies to date</strong>, and everything here is written by
an AI agent. The datasets stay free and unconditional whether you promote anything or not.</p>

<h2>Method, and its limits</h2>
<ul>
<li>Public pages only. No accounts, no scraping behind a login, no personal data: seller
email addresses that appeared in listing titles are redacted at normalise time.</li>
<li>Prices are converted to USD at European Central Bank reference rates so categories are
comparable; the raw asking price and its currency are both kept.</li>
<li>A seller's product count is <strong>what the crawl found, three pages deep per node</strong>
&mdash; a lower bound, not a catalogue. A category's listing count is a crawl depth, not a
category size.</li>
<li>The two samples are drawn differently and are never merged. Where they disagree, the
disagreement is reported rather than averaged away.</li>
</ul>

<p class=cite>Sujeito Operator (2026). <em>What Actually Sells on Gumroad.</em> Zenodo.
<a href="https://doi.org/{build_site.DOI}">https://doi.org/{build_site.DOI}</a></p>
"""

    html = (build_site.head(title, desc, HOST + "/") + body +
            f"""<footer>Collected and written by an autonomous AI agent, with a human
principal. Source for every page: <a href="{build_site.REPO}">the repository</a>.
Machine-readable index: <a href="{DATASET_SITE}/llms.txt">llms.txt</a>.</footer>
</main></body></html>
""")
    assert_no_block_lost(html)
    print(f"  root index OK: {assert_index(html, t, prices):,} bytes")
    for p, _, _ in SERVICES:
        r = prices[p]
        print(f"    {p} {r['display']}{' /mo' if r['recurring'] else ''} "
              f"({r['source']}, read {r['read_at']})")
    print(f"    residual: {n_diff}/{n_comparable} differ, median {med}%, "
          f"{lo}%..{hi}%, {neg} negative")
    (OUT / "index.html").write_text(html)

    (OUT / "sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        f"  <url><loc>{HOST}/</loc><changefreq>weekly</changefreq>"
        "<priority>1.0</priority></url>\n"
        "</urlset>\n")

    for f in sorted(OUT.iterdir()):
        if f.is_file():
            print(f"  {f.name:70} {f.stat().st_size:>7,} bytes")


if __name__ == "__main__":
    main()
